# Generated by Django 3.1.2 on 2020-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201006_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
